# Generated by Django 6.1.1 on 2026-10-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='persons',
        ),
    ]
